-- Product Clean Query
SELECT [ProductKey]
--	      ,[ProductAlternateKey]
--	      ,[ProductSubcategoryKey]
--	      ,[ProductSubcategoryKey]
--	      ,[WeightUnitMeasureCode]
--	      ,[SizeUnitMeasureCode]
      ,[EnglishProductName]
--	      ,[SpanishProductName]
--	      ,[FrenchProductName]
--	      ,[StandardCost]
--	      ,[FinishedGoodsFlag]
--	      ,[Color]
--	      ,[SafetyStockLevel]
--	      ,[ReorderPoint]
 --	     ,[ListPrice]
--	      ,[Size]
--	      ,[SizeRange]
--	      ,[Weight]
--	      ,[DaysToManufacture]
--	      ,[ProductLine]
--	      ,[DealerPrice]
--	      ,[Class]
--	      ,[Style]
--	      ,[ModelName]
--	      ,[LargePhoto]
--	      ,[EnglishDescription]
--	      ,[FrenchDescription]
--	      ,[ChineseDescription]
--	      ,[ArabicDescription]
--	      ,[HebrewDescription]
--	      ,[ThaiDescription]
--	      ,[GermanDescription]
--	      ,[JapaneseDescription]
--	      ,[TurkishDescription]
--	      ,[StartDate]
--	      ,[EndDate]
--	      ,[Status]
		  ,Prod_c.EnglishProductCategoryName AS [Category Name]
  FROM [AdventureWorksDW2019].[dbo].[DimProduct] AS Product
  LEFT JOIN dbo.DimProductSubcategory AS Prod_SC ON Prod_SC.ProductSubcategoryKey = Product.ProductSubcategoryKey
  LEFT JOIN dbo.DimProductCategory AS Prod_c ON Prod_SC.ProductCategoryKey = Prod_c.ProductCategoryKey;
  
